language: cpp
branches:
  only:
    - develop
compiler:
  - gcc
env:
# Make has issues with multiple targets and parallel builds
  - BUILD="IMP.base IMP.test" TEST=IMP.base PERCPP=base
  - BUILD="IMP.algebra IMP.kernel IMP.container" TEST=XXX PERCPP=algebra:kernel:container
  - BUILD=IMP.core TEST=XXX PERCPP=core
  - BUILD="-j 2 IMP.rmf" TEST=XXX PERCPP=rmf
  - BUILD="-j 2 IMP.atom" TEST=XXX PERCPP=atom
git:
  submodules: false

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost$BOOST-all-dev swig libhdf5-serial-dev
 - ./setup_git.py

script:
 - mkdir ../build
 - cd ../build
 - cmake ../imp -DIMP_PER_CPP_COMPILATION=$PERCPP
 - make -k $BUILD
 - ctest -j 2 -R $TEST
